#! /bin/sh
# ┏┓ ┏━┓┏━┓╻ ╻┏┳┓
# ┣┻┓┗━┓┣━┛┃╻┃┃┃┃
# ┗━┛┗━┛╹  ┗┻┛╹ ╹
# bunker@teknik.io


# startup with bspwm
sxhkd &
autocutsel &
compton &
mpd &
feh --bg-scale /home/bunker/pictures/wallpaper/liam_wong1.jpg &
$HOME/.config/polybar/launch.sh

# settings
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
